#!/usr/bin/env bash

#
# Formal environ (see `man environ`)
#

# The timezone to use when displaying dates.  The normal format is a
# pathname relative to '/usr/share/zoneinfo'
export TZ='America/New_York'

# LC_ALL overrides the values of LC_COLLATE, LC_CTYPE, LC_MESSAGES,
# LC_MONETARY, LC_NUMERIC, LC_TIME and LANG.
export LANG='en_US.UTF-8'
export LANG_ALL='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Set Sublime Text as editor
# https://www.sublimetext.com/docs/3/osx_command_line.html
if [[ -x "$(command -v subl)" ]]; then
    export EDITOR='subl -w'
else
    echo "WARNING: Could not find subl.  Setting editor to Vim" >&2
    export EDITOR='vim'
fi

# A brief 'how is my PATH obtained on macOS?' primer:
#
# - Default PATH values are obtained from /etc/paths
#   On macOS 10.15.2, this looks like:
#       /usr/local/bin
#       /usr/bin
#       /bin
#       /usr/sbin
#       /sbin
# - The internal `path_helper` utility then reads the contents of the
#   files in /etc/paths.d and appends their contents to PATH
if [[ "$(uname)" -eq "Darwin" ]]; then
    export PATH="/usr/local/sbin:${HOME}/bin:${PATH}"
fi
export PATH="${PATH}:${HOME}/.local/bin"

# LESS man page colors (makes Man pages more readable)
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

if [[ -x "$(command -v bat)" ]]; then
    export BAT_THEME='Monokai Extended Light'
fi

# use git:// instead of https:// for git clone
export USE_GIT_URI=1

# Unstaged (*) and staged (+) changes will be shown next to the branch name
# with __git_ps1
export GIT_PS1_SHOWDIRTYSTATE=1

# A '%' will be shown next to the branch name with __git_ps1 if there are
# any untracked files
export GIT_PS1_SHOWUNTRACKEDFILES=1

# Mimic --no-edit by default
export GIT_MERGE_AUTOEDIT=no

# Add the bin/ of this repo to PATH
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd | xargs dirname)"
export PATH="${PATH}:${DIR}/bin"

# Xterm with support for 256 colors enabled
export TERM=xterm-256color

# "pyenv-virtualenv: prompt changing will be removed from future release
# configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior."
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# Turn off cowsay Ansible output
export ANSIBLE_NOCOWS=1

if [[ -x "$(command -v gpg)" ]]; then
    export GPG_TTY="$(tty)"
fi

# Shell options
# https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html
shopt -s checkwinsize
shopt -s gnu_errfmt
shopt -s interactive_comments
shopt -s nocaseglob
shopt -s promptvars

# Homebrew (see `man brew`)
export HOMEBREW_BAT=1
export HOMEBREW_VERBOSE=1
